# Generated by Django 6.0.3 on 2026-04-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_booking_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="user",
        ),
    ]
